const test=require('node:test'),assert=require('node:assert/strict');
const {IDBFactory}=require('fake-indexeddb');
const J=require('../app/src/main/assets/decision-journal'),T=require('../app/src/main/assets/trainer');
const at=Date.UTC(2026,8,14,10);
function record(){return{id:'d',at,symbol:'XAUUSD',snapshot:{ok:true,schema:'closed-six-frame-v2',x:[1],names:['test'],bar:at},ai:{decision:'WAIT',reason:'UNTRAINED'},safety:{ok:true,reasons:[]},finalDecision:'WAIT',legacySide:'WAIT',positions:{BUY:J.position('BUY',{entry:100,sl:99,tp:100.75,risk:1},at)}};}
async function journal(){return new J.Journal(await J.openDB(new IDBFactory()));}
test('reimport upgrades OPEN to observed closed result and does not overwrite final labels',async()=>{const j=await journal(),r=record();await j.importDecisions([r]);J.observe(r.positions.BUY,{bid:101,ask:101.1,sourceAt:at+1000},at+1000);const result=await j.importDecisions([r]);assert.equal(result.updated,1);assert.equal(T.samples(await j.all(),'XAUUSD').length,1);r.positions.BUY.r=-9;await j.importDecisions([r]);assert.equal((await j.all())[0].positions.BUY.r,.73);j.db.close();});
test('invalid import is counted accurately even when every record is invalid',async()=>{const j=await journal(),r=await j.importDecisions([null,{id:'bad'},record()]);assert.equal(r.imported,1);assert.equal(r.skipped,2);assert.equal((await j.all()).length,1);const bad=await j.importDecisions([null]);assert.equal(bad.skipped,1);j.db.close();});
test('imports preserve rejected snapshots for diagnostics and reject malformed UI fields',async()=>{const j=await journal(),r=record();r.snapshot={ok:false,reason:'GAP_M15',x:[],names:[]};r.positions={};assert.equal((await j.importDecisions([r])).imported,1);const bad=record();bad.id='bad';delete bad.ai;assert.equal((await j.importDecisions([bad])).skipped,1);j.db.close();});
test('repeat import cannot replace a decision snapshot while updating its outcomes',async()=>{const j=await journal(),r=record();await j.importDecisions([r]);r.snapshot.x=[99];J.observe(r.positions.BUY,{bid:101,ask:101.1,sourceAt:at+1000},at+1000);await j.importDecisions([r]);assert.equal((await j.all())[0].positions.BUY.status,'OPEN');j.db.close();});
test('holdout watermark survives failed validation, repeated run and export restore',async()=>{const j=await journal(),r={runId:'a',promoted:false,reason:'INSUFFICIENT_VALIDATION_TRADES',evaluatedUntil:at};await j.commitTraining('XAUUSD',r);assert.equal(await j.meta('evaluatedUntil:XAUUSD'),at);await j.commitTraining('XAUUSD',r);await j.commitTraining('XAUUSD',{...r,runId:'b',evaluatedUntil:at-100});assert.equal(await j.meta('evaluatedUntil:XAUUSD'),at);const restored=await journal();await restored.importDecisions([],await j.metadata());assert.equal(await restored.meta('evaluatedUntil:XAUUSD'),at);j.db.close();restored.db.close();});
test('duplicates within one file do not roll back other valid records',async()=>{const j=await journal(),r=record(),result=await j.importDecisions([r,structuredClone(r)]);assert.equal(result.imported,1);assert.equal(result.skipped,1);assert.equal((await j.all()).length,1);j.db.close();});
test('nonterminal imported outcomes normalize unavailable R before rendering',async()=>{const j=await journal(),r=record();delete r.positions.BUY.r;await j.importDecisions([r]);assert.equal((await j.all())[0].positions.BUY.r,null);j.db.close();});
test('merged exports retain the highest holdout watermark within one import',async()=>{const j=await journal();await j.importDecisions([],[{id:'evaluatedUntil:XAUUSD',value:2000},{id:'evaluatedUntil:XAUUSD',value:1000}]);assert.equal(await j.meta('evaluatedUntil:XAUUSD'),2000);j.db.close();});
